name: Publish Nuget package

on: 
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
                
      - name: Build
        run: dotnet build --configuration Release
        shell: bash
        
      - name: Publish KafkaPoller Nuget release package
        shell: bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push src/KafkaPoller/bin/Release/KafkaPoller.*.*.*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
