name: Publish Nuget prerelease package

on:
  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: dotnet build --configuration Release --version-suffix -prerelease-$(date +%Y%m%d%H%M%S)
        shell: bash

      - name: Publish KafkaPoller Nuget pre-release package
        shell: bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push src/KafkaPoller/bin/Release/KafkaPoller.*.*.*-prerelease-*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
